#!/bin/bash

HOST_IP_FILE="/etc/hostip"

if [ -f $HOST_IP_FILE ]
then
    export HOST_IP=$(cat $HOST_IP_FILE)    
fi


if [[ ! -e "$APP_PORT" ]]
then
    PORT_KEY="$APP_PORT/tcp"
    export HOST_PORT=$(docker inspect --format="{{(index (index .NetworkSettings.Ports \"$PORT_KEY\") 0).HostPort}}" $HOSTNAME)
fi

exec "$@"